### ISSUE TITLE
error info

### ISSUE THREAD

**Issue by byxiaoxie** [ddakebono/PalworldRcon#11]
2024-01-29 15:17:18.485 [Info] - Startup
2024-01-29 15:17:18.641 [Info] - Welcome to Bono's Palworld Rcon Tool!
2024-01-29 15:17:18.641 [Warning] - Using this console allows you to send any commands to the server, please ensure you know what you're about to send!
2024-01-29 15:17:59.126 [Error] - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.BitConverter.ToInt32(Byte[] value, Int32 startIndex)
   at PalworldRcon.Network.RconPacket..ctor(Byte[] data)
2024-01-29 15:17:59.129 [Info] - OnDisconnect called
2024-01-29 15:17:59.131 [Info] -

**Comment by ddakebono** [comment]
This issue should be fixed in 1.2.0 as I've migrated to CoreRCON, which directly supports Palworld and should properly handle it's jank
